name: 'Docker Build and Push'

description: 'Build Docker image and push to Docker Hub'

inputs:
  dockerfile:
    description: 'Specify a custom Dockerfile. Defaults to Dockerfile.'
    required: false
    default: ''
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub token'
    required: true
  repository-name:
    description: 'Repository name'
    required: true
  environment:
    description: 'Deployment environment'
    default: 'prod'
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Checkout Repository
      uses: actions/checkout@master
      with:
        ref: main

    - name: Autotag
      id: autotag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.dockerhub-username }}/{{ inputs.repository-name }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile || 'Dockerfile' }}
        push: true
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.repository-name }}:${{ inputs.environment }}-latest,${{ inputs.dockerhub-username }}/${{ inputs.repository-name }}:${{ inputs.environment }}-${{ steps.autotag.outputs.tag }}
        labels: ${{ steps.metadata.outputs.labels }}